
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=Hello
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=custom-token
    volumes:
      - ./influxdb/token:/token_storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086"]
      interval: 10s
      timeout: 5s
      retries: 3

  compensator_device:
    image: alpine
    command: sh -c "cp /source/compensator_device.json /data/"
    volumes:
      - compensator_data:/data
      - ./compensator_device:/source:ro
    restart: "no"

  ntp:
    build: ./ntp
    container_name: ntp
    depends_on:
      influxdb:
        condition: service_healthy
    ports:
      - "4000:4000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_BUCKET=Hello
      - INFLUXDB_TOKEN_FILE=/token_storage/token.txt
    volumes:
      - ./influxdb/token:/token_storage
      - shared_excel_data:/shared_volume
      - compensator_data:/app/data

  envvarco:
    build:
      context: .
      dockerfile: envvarco/Dockerfile
    container_name: envvarco
    ports:
      - "4002:4002"
    volumes:
      - shared_excel_data:/shared_volume
      - compensator_data:/app/data
      - ./base_system:/shared_volume_base:ro

  bus_priority_score:
    build:
      context: .
      dockerfile: bus_priority_score/Dockerfile
    container_name: bus_priority_score
    ports:
      - "4003:4003"
    volumes:
      - shared_excel_data:/shared_volume
      - compensator_data:/app/data
      - ./base_system:/shared_volume_base:ro

  trigger_var_control:
    build:
      context: .
      dockerfile: trigger_var_control/Dockerfile
    container_name: trigger_var_control
    ports:
      - "4004:4004"
    volumes:
      - shared_excel_data:/shared_volume
      - compensator_data:/app/data
      - ./base_system:/shared_volume_base:ro

  base_network:
    build:
      context: .
      dockerfile: base_network/Dockerfile
    container_name: base_network
    ports:
      - "4006:4006"
    volumes:
      - shared_excel_data:/shared_volume
      - compensator_data:/app/data
      - ./base_system:/shared_volume_base

  auto_reclosure:
      build:
        context: .
        dockerfile: auto_reclosure/Dockerfile
      container_name: auto_reclosure
      ports:
        - "4007:4007"
      volumes:
        - shared_excel_data:/shared_volume
        - compensator_data:/app/data
        - ./base_system:/shared_volume_base:ro

  service_restoration:
      build:
        context: .
        dockerfile: service_restoration/Dockerfile
      container_name: service_restoration
      ports:
        - "4005:4005"
      volumes:
        - shared_excel_data:/shared_volume
        - compensator_data:/app/data
        - ./base_system:/shared_volume_base:ro
        
  grafana:
    build: ./grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards/main

volumes:
  shared_excel_data:
    name: shared_excel_data
  compensator_data:
    name: compensator_data